
package za.ac.tut.clientsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductPort", targetNamespace = "http://webservice.tut.ac.za/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductPort {


    /**
     * 
     * @param arg0
     * @return
     *     returns za.ac.tut.clientsoap.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.GetProductResponse")
    @Action(input = "http://webservice.tut.ac.za/ProductPort/getProductRequest", output = "http://webservice.tut.ac.za/ProductPort/getProductResponse")
    public Product getProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.DeleteProductResponse")
    @Action(input = "http://webservice.tut.ac.za/ProductPort/deleteProductRequest", output = "http://webservice.tut.ac.za/ProductPort/deleteProductResponse")
    public String deleteProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.InsertResponse")
    @Action(input = "http://webservice.tut.ac.za/ProductPort/insertRequest", output = "http://webservice.tut.ac.za/ProductPort/insertResponse")
    public String insert(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initialiseBean", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.InitialiseBean")
    @ResponseWrapper(localName = "initialiseBeanResponse", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.InitialiseBeanResponse")
    @Action(input = "http://webservice.tut.ac.za/ProductPort/initialiseBeanRequest", output = "http://webservice.tut.ac.za/ProductPort/initialiseBeanResponse")
    public void initialiseBean();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://webservice.tut.ac.za/", className = "za.ac.tut.clientsoap.UpdateProductResponse")
    @Action(input = "http://webservice.tut.ac.za/ProductPort/updateProductRequest", output = "http://webservice.tut.ac.za/ProductPort/updateProductResponse")
    public String updateProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        Product arg0);

}
